# Generated by Django 6.0.5 on 2026-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_paydebt_product_importproduct_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paydebt',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='paydebt',
            name='client',
        ),
        migrations.RemoveField(
            model_name='paydebt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ImportProduct',
        ),
        migrations.DeleteModel(
            name='PayDebt',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
