# Generated by Django 6.0.5 on 2026-05-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch'),
        ),
    ]
